### ISSUE TITLE
Can't read property of hash when adding plugin

### ISSUE THREAD

**Issue by DerArkeN** [Richienb/node-polyfill-webpack-plugin#21]
`D:\Aaron\Coding\untis-google-web\node_modules\webpack\lib\NormalModule.js:1353
                hash.update(this.buildInfo.hash);
                                           ^

TypeError: Cannot read properties of undefined (reading 'hash')
    at NormalModule.updateHash (D:\Aaron\Coding\untis-google-web\node_modules\webpack\lib\NormalModule.js:1353:30)
    at Compilation._createModuleHash (D:\Aaron\Coding\untis-google-web\node_modules\webpack\lib\Compilation.js:3935:10)
    at Compilation.createModuleHashes (D:\Aaron\Coding\untis-google-web\node_modules\webpack\lib\Compilation.js:3902:25)
    at D:\Aaron\Coding\untis-google-web\node_modules\webpack\lib\Compilation.js:3009:11
    at Hook.eval [as callAsync] (eval at create (D:\Aaron\Coding\untis-google-web\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Aaron\Coding\untis-google-web\node_modules\tapable\lib\Hook.js:18:14)
    at D:\Aaron\Coding\untis-google-web\node_modules\webpack\lib\Compilation.js:2965:36
    at Hook.eval [as callAsync] (eval at create (D:\Aaron\Coding\untis-google-web\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Aaron\Coding\untis-google-web\node_modules\tapable\lib\Hook.js:18:14)
    at Compilation.seal (D:\Aaron\Coding\untis-google-web\node_modules\webpack\lib\Compilation.js:2956:27)`
    
    after adding the plugin to the webpack config.

**Comment by Richienb** [comment]
Try this solution: https://github.com/mzgoddard/hard-source-webpack-plugin/issues/416#issuecomment-411832075
